//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//


package by.epamlab.xjc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FlightSupplementalInfo" type="{http://www.epamlab.by/Velichko/Valentine}FlightSupplementalInfoType" minOccurs="0"/&gt;
 *         &lt;element name="BookingClassAvailability" type="{http://www.epamlab.by/Velichko/Valentine}BookingClassAvailabilityType" minOccurs="0"/&gt;
 *         &lt;element name="Eticket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TerminalInformation" type="{http://www.epamlab.by/Velichko/Valentine}TerminalInformationType" minOccurs="0"/&gt;
 *         &lt;element name="InventorySystem" type="{http://www.epamlab.by/Velichko/Valentine}InventorySystemType" minOccurs="0"/&gt;
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Attributes" type="{http://www.epamlab.by/Velichko/Valentine}AttributesType" minOccurs="0"/&gt;
 *         &lt;element name="Base" type="{http://www.epamlab.by/Velichko/Valentine}BaseType" minOccurs="0"/&gt;
 *         &lt;element name="TaxInfos" type="{http://www.epamlab.by/Velichko/Valentine}TaxInfosType" minOccurs="0"/&gt;
 *         &lt;element name="FeeInfos" type="{http://www.epamlab.by/Velichko/Valentine}FeeInfosType" minOccurs="0"/&gt;
 *         &lt;element name="Total" type="{http://www.epamlab.by/Velichko/Valentine}TotalType" minOccurs="0"/&gt;
 *         &lt;element name="Segment" type="{http://www.epamlab.by/Velichko/Valentine}SegmentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Passenger" type="{http://www.epamlab.by/Velichko/Valentine}PassengerType" minOccurs="0"/&gt;
 *         &lt;element name="Carrier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PricingSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Provider" type="{http://www.epamlab.by/Velichko/Valentine}ProviderType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionType", propOrder = {
    "flightSupplementalInfo",
    "bookingClassAvailability",
    "eticket",
    "terminalInformation",
    "inventorySystem",
    "source",
    "attributes",
    "base",
    "taxInfos",
    "feeInfos",
    "total",
    "segment",
    "passenger",
    "carrier",
    "pricingSystem",
    "provider"
})
public class ExtensionType {

    @XmlElement(name = "FlightSupplementalInfo")
    protected FlightSupplementalInfoType flightSupplementalInfo;
    @XmlElement(name = "BookingClassAvailability")
    protected BookingClassAvailabilityType bookingClassAvailability;
    @XmlElement(name = "Eticket")
    protected String eticket;
    @XmlElement(name = "TerminalInformation")
    protected TerminalInformationType terminalInformation;
    @XmlElement(name = "InventorySystem")
    protected InventorySystemType inventorySystem;
    @XmlElement(name = "Source")
    protected String source;
    @XmlElement(name = "Attributes")
    protected AttributesType attributes;
    @XmlElement(name = "Base")
    protected BaseType base;
    @XmlElement(name = "TaxInfos")
    protected TaxInfosType taxInfos;
    @XmlElement(name = "FeeInfos")
    protected FeeInfosType feeInfos;
    @XmlElement(name = "Total")
    protected TotalType total;
    @XmlElement(name = "Segment")
    protected List<SegmentType> segment;
    @XmlElement(name = "Passenger")
    protected PassengerType passenger;
    @XmlElement(name = "Carrier")
    protected String carrier;
    @XmlElement(name = "PricingSystem")
    protected String pricingSystem;
    @XmlElement(name = "Provider")
    protected ProviderType provider;

    /**
     * Gets the value of the flightSupplementalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FlightSupplementalInfoType }
     *     
     */
    public FlightSupplementalInfoType getFlightSupplementalInfo() {
        return flightSupplementalInfo;
    }

    /**
     * Sets the value of the flightSupplementalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightSupplementalInfoType }
     *     
     */
    public void setFlightSupplementalInfo(FlightSupplementalInfoType value) {
        this.flightSupplementalInfo = value;
    }

    /**
     * Gets the value of the bookingClassAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link BookingClassAvailabilityType }
     *     
     */
    public BookingClassAvailabilityType getBookingClassAvailability() {
        return bookingClassAvailability;
    }

    /**
     * Sets the value of the bookingClassAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingClassAvailabilityType }
     *     
     */
    public void setBookingClassAvailability(BookingClassAvailabilityType value) {
        this.bookingClassAvailability = value;
    }

    /**
     * Gets the value of the eticket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEticket() {
        return eticket;
    }

    /**
     * Sets the value of the eticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEticket(String value) {
        this.eticket = value;
    }

    /**
     * Gets the value of the terminalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TerminalInformationType }
     *     
     */
    public TerminalInformationType getTerminalInformation() {
        return terminalInformation;
    }

    /**
     * Sets the value of the terminalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminalInformationType }
     *     
     */
    public void setTerminalInformation(TerminalInformationType value) {
        this.terminalInformation = value;
    }

    /**
     * Gets the value of the inventorySystem property.
     * 
     * @return
     *     possible object is
     *     {@link InventorySystemType }
     *     
     */
    public InventorySystemType getInventorySystem() {
        return inventorySystem;
    }

    /**
     * Sets the value of the inventorySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventorySystemType }
     *     
     */
    public void setInventorySystem(InventorySystemType value) {
        this.inventorySystem = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link BaseType }
     *     
     */
    public BaseType getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseType }
     *     
     */
    public void setBase(BaseType value) {
        this.base = value;
    }

    /**
     * Gets the value of the taxInfos property.
     * 
     * @return
     *     possible object is
     *     {@link TaxInfosType }
     *     
     */
    public TaxInfosType getTaxInfos() {
        return taxInfos;
    }

    /**
     * Sets the value of the taxInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxInfosType }
     *     
     */
    public void setTaxInfos(TaxInfosType value) {
        this.taxInfos = value;
    }

    /**
     * Gets the value of the feeInfos property.
     * 
     * @return
     *     possible object is
     *     {@link FeeInfosType }
     *     
     */
    public FeeInfosType getFeeInfos() {
        return feeInfos;
    }

    /**
     * Sets the value of the feeInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeInfosType }
     *     
     */
    public void setFeeInfos(FeeInfosType value) {
        this.feeInfos = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link TotalType }
     *     
     */
    public TotalType getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalType }
     *     
     */
    public void setTotal(TotalType value) {
        this.total = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentType }
     * 
     * 
     */
    public List<SegmentType> getSegment() {
        if (segment == null) {
            segment = new ArrayList<SegmentType>();
        }
        return this.segment;
    }

    /**
     * Gets the value of the passenger property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerType }
     *     
     */
    public PassengerType getPassenger() {
        return passenger;
    }

    /**
     * Sets the value of the passenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerType }
     *     
     */
    public void setPassenger(PassengerType value) {
        this.passenger = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the pricingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingSystem() {
        return pricingSystem;
    }

    /**
     * Sets the value of the pricingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingSystem(String value) {
        this.pricingSystem = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderType }
     *     
     */
    public ProviderType getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderType }
     *     
     */
    public void setProvider(ProviderType value) {
        this.provider = value;
    }

}
