//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//


package by.epamlab.xjc;

import java.math.BigInteger;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ItineraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Air" type="{http://www.epamlab.by/Velichko/Valentine}AirType"/&gt;
 *         &lt;element name="PricingInfo" type="{http://www.epamlab.by/Velichko/Valentine}PricingInfoType"/&gt;
 *         &lt;element name="TicketingInfo" type="{http://www.epamlab.by/Velichko/Valentine}TicketingInfoType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SequenceNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="RPH" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ItineraryID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Itinerary")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryType", propOrder = {
    "air",
    "pricingInfo",
    "ticketingInfo"
})
public class ItineraryType {

    @XmlElement(name = "Air", required = true)
    protected AirType air;
    @XmlElement(name = "PricingInfo", required = true)
    protected PricingInfoType pricingInfo;
    @XmlElement(name = "TicketingInfo", required = true)
    protected TicketingInfoType ticketingInfo;
    @XmlAttribute(name = "SequenceNumber", required = true)
    protected BigInteger sequenceNumber;
    @XmlAttribute(name = "RPH", required = true)
    protected BigInteger rph;
    @XmlAttribute(name = "ItineraryID", required = true)
    protected BigInteger itineraryID;

    /**
     * Gets the value of the air property.
     * 
     * @return
     *     possible object is
     *     {@link AirType }
     *     
     */
    public AirType getAir() {
        return air;
    }

    /**
     * Sets the value of the air property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirType }
     *     
     */
    public void setAir(AirType value) {
        this.air = value;
    }

    /**
     * Gets the value of the pricingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PricingInfoType }
     *     
     */
    public PricingInfoType getPricingInfo() {
        return pricingInfo;
    }

    /**
     * Sets the value of the pricingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingInfoType }
     *     
     */
    public void setPricingInfo(PricingInfoType value) {
        this.pricingInfo = value;
    }

    /**
     * Gets the value of the ticketingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TicketingInfoType }
     *     
     */
    public TicketingInfoType getTicketingInfo() {
        return ticketingInfo;
    }

    /**
     * Sets the value of the ticketingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketingInfoType }
     *     
     */
    public void setTicketingInfo(TicketingInfoType value) {
        this.ticketingInfo = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the rph property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPH() {
        return rph;
    }

    /**
     * Sets the value of the rph property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPH(BigInteger value) {
        this.rph = value;
    }

    /**
     * Gets the value of the itineraryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getItineraryID() {
        return itineraryID;
    }

    /**
     * Sets the value of the itineraryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setItineraryID(BigInteger value) {
        this.itineraryID = value;
    }

}
