//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//


package by.epamlab.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.epamlab.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Itinerary_QNAME = new QName("http://www.epamlab.by/Velichko/Valentine", "Itinerary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.epamlab.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PassengerType }
     * 
     */
    public PassengerType createPassengerType() {
        return new PassengerType();
    }

    /**
     * Create an instance of {@link FeeInfosType }
     * 
     */
    public FeeInfosType createFeeInfosType() {
        return new FeeInfosType();
    }

    /**
     * Create an instance of {@link FeesType }
     * 
     */
    public FeesType createFeesType() {
        return new FeesType();
    }

    /**
     * Create an instance of {@link ItineraryType }
     * 
     */
    public ItineraryType createItineraryType() {
        return new ItineraryType();
    }

    /**
     * Create an instance of {@link AirType }
     * 
     */
    public AirType createAirType() {
        return new AirType();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link FlightType }
     * 
     */
    public FlightType createFlightType() {
        return new FlightType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link FlightSupplementalInfoType }
     * 
     */
    public FlightSupplementalInfoType createFlightSupplementalInfoType() {
        return new FlightSupplementalInfoType();
    }

    /**
     * Create an instance of {@link BookingClassAvailabilityType }
     * 
     */
    public BookingClassAvailabilityType createBookingClassAvailabilityType() {
        return new BookingClassAvailabilityType();
    }

    /**
     * Create an instance of {@link TerminalInformationType }
     * 
     */
    public TerminalInformationType createTerminalInformationType() {
        return new TerminalInformationType();
    }

    /**
     * Create an instance of {@link InventorySystemType }
     * 
     */
    public InventorySystemType createInventorySystemType() {
        return new InventorySystemType();
    }

    /**
     * Create an instance of {@link AttributesType }
     * 
     */
    public AttributesType createAttributesType() {
        return new AttributesType();
    }

    /**
     * Create an instance of {@link PricingInfoType }
     * 
     */
    public PricingInfoType createPricingInfoType() {
        return new PricingInfoType();
    }

    /**
     * Create an instance of {@link TotalType }
     * 
     */
    public TotalType createTotalType() {
        return new TotalType();
    }

    /**
     * Create an instance of {@link BaseType }
     * 
     */
    public BaseType createBaseType() {
        return new BaseType();
    }

    /**
     * Create an instance of {@link TaxesType }
     * 
     */
    public TaxesType createTaxesType() {
        return new TaxesType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link TaxInfosType }
     * 
     */
    public TaxInfosType createTaxInfosType() {
        return new TaxInfosType();
    }

    /**
     * Create an instance of {@link TaxInfoType }
     * 
     */
    public TaxInfoType createTaxInfoType() {
        return new TaxInfoType();
    }

    /**
     * Create an instance of {@link PTCsType }
     * 
     */
    public PTCsType createPTCsType() {
        return new PTCsType();
    }

    /**
     * Create an instance of {@link PTCType }
     * 
     */
    public PTCType createPTCType() {
        return new PTCType();
    }

    /**
     * Create an instance of {@link PassengerQuantityType }
     * 
     */
    public PassengerQuantityType createPassengerQuantityType() {
        return new PassengerQuantityType();
    }

    /**
     * Create an instance of {@link BasisCodesType }
     * 
     */
    public BasisCodesType createBasisCodesType() {
        return new BasisCodesType();
    }

    /**
     * Create an instance of {@link PassengerFareType }
     * 
     */
    public PassengerFareType createPassengerFareType() {
        return new PassengerFareType();
    }

    /**
     * Create an instance of {@link FareInfosType }
     * 
     */
    public FareInfosType createFareInfosType() {
        return new FareInfosType();
    }

    /**
     * Create an instance of {@link FareInfoType }
     * 
     */
    public FareInfoType createFareInfoType() {
        return new FareInfoType();
    }

    /**
     * Create an instance of {@link SegmentType }
     * 
     */
    public SegmentType createSegmentType() {
        return new SegmentType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link TicketingInfoType }
     * 
     */
    public TicketingInfoType createTicketingInfoType() {
        return new TicketingInfoType();
    }

    /**
     * Create an instance of {@link PassengerType.RemoteSystemPTCs }
     * 
     */
    public PassengerType.RemoteSystemPTCs createPassengerTypeRemoteSystemPTCs() {
        return new PassengerType.RemoteSystemPTCs();
    }

    /**
     * Create an instance of {@link FeeInfosType.FeeInfo }
     * 
     */
    public FeeInfosType.FeeInfo createFeeInfosTypeFeeInfo() {
        return new FeeInfosType.FeeInfo();
    }

    /**
     * Create an instance of {@link FeesType.Fee }
     * 
     */
    public FeesType.Fee createFeesTypeFee() {
        return new FeesType.Fee();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItineraryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ItineraryType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.epamlab.by/Velichko/Valentine", name = "Itinerary")
    public JAXBElement<ItineraryType> createItinerary(ItineraryType value) {
        return new JAXBElement<ItineraryType>(_Itinerary_QNAME, ItineraryType.class, null, value);
    }

}
