//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.epamlab.by/Velichko/Valentine", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.epamlab.xjc;
