//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//


package by.epamlab.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Total" type="{http://www.epamlab.by/Velichko/Valentine}TotalType"/&gt;
 *         &lt;element name="PTCs" type="{http://www.epamlab.by/Velichko/Valentine}PTCsType"/&gt;
 *         &lt;element name="FareInfos" type="{http://www.epamlab.by/Velichko/Valentine}FareInfosType"/&gt;
 *         &lt;element name="Extension" type="{http://www.epamlab.by/Velichko/Valentine}ExtensionType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingInfoType", propOrder = {
    "total",
    "ptCs",
    "fareInfos",
    "extension"
})
public class PricingInfoType {

    @XmlElement(name = "Total", required = true)
    protected TotalType total;
    @XmlElement(name = "PTCs", required = true)
    protected PTCsType ptCs;
    @XmlElement(name = "FareInfos", required = true)
    protected FareInfosType fareInfos;
    @XmlElement(name = "Extension", required = true)
    protected ExtensionType extension;
    @XmlAttribute(name = "Source", required = true)
    protected String source;

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link TotalType }
     *     
     */
    public TotalType getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalType }
     *     
     */
    public void setTotal(TotalType value) {
        this.total = value;
    }

    /**
     * Gets the value of the ptCs property.
     * 
     * @return
     *     possible object is
     *     {@link PTCsType }
     *     
     */
    public PTCsType getPTCs() {
        return ptCs;
    }

    /**
     * Sets the value of the ptCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PTCsType }
     *     
     */
    public void setPTCs(PTCsType value) {
        this.ptCs = value;
    }

    /**
     * Gets the value of the fareInfos property.
     * 
     * @return
     *     possible object is
     *     {@link FareInfosType }
     *     
     */
    public FareInfosType getFareInfos() {
        return fareInfos;
    }

    /**
     * Sets the value of the fareInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FareInfosType }
     *     
     */
    public void setFareInfos(FareInfosType value) {
        this.fareInfos = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
