//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.23 at 02:05:18 AM MSK 
//


package by.epamlab.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PTCType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PTCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PassengerQuantity" type="{http://www.epamlab.by/Velichko/Valentine}PassengerQuantityType"/&gt;
 *         &lt;element name="BasisCodes" type="{http://www.epamlab.by/Velichko/Valentine}BasisCodesType"/&gt;
 *         &lt;element name="PassengerFare" type="{http://www.epamlab.by/Velichko/Valentine}PassengerFareType"/&gt;
 *         &lt;element name="Extension" type="{http://www.epamlab.by/Velichko/Valentine}ExtensionType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PTCType", propOrder = {
    "passengerQuantity",
    "basisCodes",
    "passengerFare",
    "extension"
})
public class PTCType {

    @XmlElement(name = "PassengerQuantity", required = true)
    protected PassengerQuantityType passengerQuantity;
    @XmlElement(name = "BasisCodes", required = true)
    protected BasisCodesType basisCodes;
    @XmlElement(name = "PassengerFare", required = true)
    protected PassengerFareType passengerFare;
    @XmlElement(name = "Extension", required = true)
    protected ExtensionType extension;
    @XmlAttribute(name = "Source", required = true)
    protected String source;

    /**
     * Gets the value of the passengerQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerQuantityType }
     *     
     */
    public PassengerQuantityType getPassengerQuantity() {
        return passengerQuantity;
    }

    /**
     * Sets the value of the passengerQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerQuantityType }
     *     
     */
    public void setPassengerQuantity(PassengerQuantityType value) {
        this.passengerQuantity = value;
    }

    /**
     * Gets the value of the basisCodes property.
     * 
     * @return
     *     possible object is
     *     {@link BasisCodesType }
     *     
     */
    public BasisCodesType getBasisCodes() {
        return basisCodes;
    }

    /**
     * Sets the value of the basisCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasisCodesType }
     *     
     */
    public void setBasisCodes(BasisCodesType value) {
        this.basisCodes = value;
    }

    /**
     * Gets the value of the passengerFare property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerFareType }
     *     
     */
    public PassengerFareType getPassengerFare() {
        return passengerFare;
    }

    /**
     * Sets the value of the passengerFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerFareType }
     *     
     */
    public void setPassengerFare(PassengerFareType value) {
        this.passengerFare = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
